version: '2'
services:
  flowershop-app:
    image: flowershop
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://flowershop-mysql:3306/flowershop?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://flowershop-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://flowershop-elasticsearch:9200
    ports:
      - 8080:8080
  flowershop-mysql:
    extends:
      file: mysql.yml
      service: flowershop-mysql
  flowershop-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: flowershop-elasticsearch
